[tasks.run]
command = "cargo"
args = ["run", "--release"]

[tasks.generate_img]
command = "convert"
args = ["output.ppm", "par.png"]
dependencies = ["run"]

[tasks.open_feh]
command = "feh"
args = ["par.png"]
dependencies = [
    "generate_img"
]

[tasks.my-penis-hard]
dependencies =[
  "open_feh"
]
